#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR

java -jar target/helloworld-0.0.1-SNAPSHOT.jar server helloworld.yml
